### ISSUE TITLE
Provider authentication details/examples?

### ISSUE THREAD

**Issue by jcogilvie** [oboukili/terraform-provider-argocd#267]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version
```
Terraform version: 1.4.5
ArgoCD provider version: none yet
ArgoCD version: 2.6.7
```

## Terraform configuration
None yet

## Question
I'm adopting argo and looking to plan my authentication path for the provider, but the documentation isn't really clear on which sets of options go together by way of examples.

For instance, I know that I could authenticate with a token or user/pass, and that will probably satisfy the constraints.  But if I authenticate with `kubernetes` (similarly to the `kubernetes` or `helm` providers) do I still need to auth to argo separately, or is a kube administrator enough?  

I can make a machine user in argo and store a token and go through a public access point to argo, but I'm trying to limit authentication to my oauth provider so I don't want to do that unless it's necessary (hence asking about the kubernetes auth path).

**Comment by onematchfox** [comment]
Hi @jcogilvie,

Agreed, the provider docs are lacking in this area, and this is one of the largest sources of issues that are opened here. The short answer to the question is that you should be able to use the same settings as whatever you use when calling `argocd login`, and so ideally, we could simply reference/copy examples in the [ArgoCD CLI docs](https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_login/). However, you'll notice that those are slim on examples as well. :disappointed: 

Having not used the `kubernetes` block myself I am not the best person to provide guidance here. However, my understanding is that this is not actually used for authentication with the ArgoCD API. Instead, it is used to authenticate with the Kubernetes API in order to temporarily expose the API server (using port-forwarding). This is useful for users that have not exposed the API server in another way (e.g. via LB/Ingress). So, this means you would still need to supply a username+password/auth token. I tried playing around quickly with the `argocd` CLI, and what I saw seemed to confirm this behaviour. See also the Getting Started docs [here](https://argo-cd.readthedocs.io/en/stable/getting_started/#3-access-the-argo-cd-api-server). I would be happy to be corrected if I am wrong. On that note, we would welcome any contributions in this area! Any examples can be added to the [example here](https://github.com/oboukili/terraform-provider-argocd/blob/master/examples/provider/provider.tf) to be included in the (generated) docs that get published to the Terraform registry.
